# Generated by Django 2.1.3 on 2018-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=30, verbose_name='Activity Name')),
                ('reward_object', models.CharField(max_length=30, verbose_name='The one who gets the points')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Activity Date')),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'reward',
            },
        ),
    ]
