# Generated by Django 2.1.3 on 2018-12-28 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('student_email', models.EmailField(max_length=30)),
                ('student_number', models.IntegerField(max_length=7)),
                ('qrCode', models.ImageField(upload_to=None)),
                ('profile_picture', models.ImageField(upload_to=None)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(12)])),
                ('home_room', models.CharField(max_length=3)),
                ('student_points', models.IntegerField(default=0, verbose_name='points')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
                ('student_description', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=30, verbose_name='Activity Name')),
                ('reward_object', models.CharField(max_length=30, verbose_name='The one who gets the points')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Activity Date')),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'reward',
            },
        ),
    ]
