# Generated by Django 2.1.3 on 2018-12-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='reward_object',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qrCode',
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(default="You don't have any description yet", max_length=300),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_description',
            field=models.TextField(default="You don't have any description yet", max_length=300),
        ),
    ]
